# -*- coding: utf-8 -*-
"""week 4 dv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ranjithkumar200869-create/DV-SKILLS/blob/main/WEEK%204/week%204%20dv.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data= pd.read_excel("/content/AAPL.xlsx")

data.head()

data.tail()

data.columns

data.dtypes

data["Date"] = pd.to_datetime(data["Date"],utc=True)
data['Date'].dtype

data-data.sort_values("Date")

data["Date"] = pd.to_datetime(data["Date"],utc=True)
data

plt.figure(figsize=(16, 8))
plt.plot(data['Date'], data["Open"], label="Open", color="purple")
plt.plot(data['Date'], data["High"], label="High", color="deeppink")
plt.plot(data['Date'], data["Low"], label="Low", color="grey")
plt.plot(data['Date'], data["Close"], label="Close", color="brown")
plt.title("OHLC PRICE")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()

plt.figure(figsize=(16,8))
plt.plot(data["Date"],data["Volume"],color="purple")
plt.title("VOLUME ANALYSIS")
plt.xlabel("Date")
plt.ylabel("Volume of trade shares")
plt.show()

data["MA20"] = data["Close"].rolling(window=20).mean()
plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data["MA20"], label="20-Day MA", color="grey")
plt.title("20 days")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

data["MA50"] = data["Close"].rolling(window=50).mean()
plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data["MA50"], label="50-Day MA",color="grey")
plt.title("50 days")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()