# -*- coding: utf-8 -*-
"""dv 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ranjithkumar200869-create/DV-SKILLS/blob/main/WEEK%207/dv%207.ipynb
"""

import pandas as pd

df=pd.read_csv("StudentsPerformance.csv")

categorical_cols=[
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]
for col in categorical_cols:
    df[col] = df[col].str.strip().str.title()
df[categorical_cols].head()

score_cols = [
    "math score",
    "reading score",
    "writing score"
]

print("Statistical Measures:")
for col in score_cols:
  print(f"\n{col}")
  print("Mean: ", df[col].mean())
  print("Median: ", df[col].median())
  print("Mode: ", df[col].mode().iloc[0])

