# -*- coding: utf-8 -*-
"""week 6 dv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ranjithkumar200869-create/DV-SKILLS/blob/main/WEEK%206/week%206%20dv.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/healthcare_dataset.csv")

df.head()

df.columns

df.columns

df.dtypes

df.isnull()

df.isnull().sum()

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], dayfirst=True)
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], dayfirst=True)

df["stay Duration"] = (
    df["Discharge_Date"] - df["Admission_Date"]
).dt.days
df.head()

billing = df.groupby(["Medical_Condition"])["Billing_Amount"].sum()

data = df.groupby(
    ["Medical_Condition"]
)["Billing_Amount"].mean()

data.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Average Billing Amount by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Average Billing Amount")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x="Medical_Condition",
    y="Billing_Amount"
)

plt.title("Billing Amount Distribution by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x="Gender",
    y="Billing_Amount"
)

plt.title("Billing Amount Distribution by Gender")
plt.xlabel("Gender")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df['Admission'] = df['Admission_Date'].dt.month

plt.figure(figsize=(12,6))
Monthly_Admission = df.groupby('Admission').size()
Monthly_Admission.plot(kind="line",marker="o")

plt.title("Monthly Patient Admission")
plt.xlabel("Month")
plt.ylabel("Number of Admissions")
plt.xticks(rotation=45)
plt.grid()

correlation_matrix = df.corr(numeric_only=True)
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()