# -*- coding: utf-8 -*-
"""WEEK 1 ASSESMENT (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ranjithkumar200869-create/DV-SKILLS/blob/main/WEEK%203/WEEK%201%20ASSESMENT%20(1).ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded=files.upload()

df = pd.read_excel("AAPL.xlsx")

print("First 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

print("\nDataset information:")
print(df.info())

print("\nDataset shape:")
print(df.shape)

print("\nColumn name:")
print(df.columns)

print("\nData types:")
print(df.dtypes)

print("\nmissing values:")
print(df.isnull().sum())

print(df.columns.tolist())

df = df.sort_values('Date')

df["Daily_Return"] = df["Close"].pct_change() * 100

