# -*- coding: utf-8 -*-
"""week 5 dv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ranjithkumar200869-create/DV-SKILLS/blob/main/WEEK%205/week%205%20dv.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/healthcare_dataset (1).csv")

df.head()

df.columns

df.shape

df.dtypes

df.isnull()

df.isnull().sum()

df['Medical Condition'].isnull().sum()

df['Date of Admission']=pd.to_datetime(df['Date of Admission'])
df['Date of Admission']

df['Discharge Date']=pd.to_datetime(df['Discharge Date'])
df['Discharge Date']

df['Admission Type'].value_counts()

df['Admission Type'] = (
    df['Admission Type']
    .str.lower()
)

df['Admission Type'] = (
    df['Admission Type']
    .str.lower()
)
df['Admission Type'].value_counts()

df["Admission Type"]

df["Billing Amount"].describe()