# -*- coding: utf-8 -*-
"""Superstore-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ranjithkumar200869-create/DV-SKILLS/blob/main/WEEK%202/Superstore-2.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/BIG DATA /SuperStore.csv.csv")

df.head()

df.info()

df.describe()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df.info()

df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days

df.head()

df.isnull().sum()

category_sales = (df.groupby('Category')['Sales Amount'].sum())
category_sales

category_sales.plot( kind='bar',figsize=(8,5))
plt.title("Sales by Category")
plt.ylabel("Total Sales")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['Sales Amount'],bins=30)
plt.title("Sales Distribution")
plt.show()

"""Bar Plot"""

sns.barplot(
    data=df,
    x="Category",
    y="Profit"
)

plt.title("Profit by Category")
plt.show()

sns.barplot(
    data=df,
    x="Category",
    y="Sales"
)

plt.title("Sales Distribution by Category")
plt.show()

"""Box Plot"""

sns.boxplot(
    data=df,
    y="Profit"
)

plt.title("Profit Distribution")
plt.show()

sns.boxplot(
    data=df,
    x="Category",
    y="Profit"
)

plt.title("Profit Variation Across Categories")
plt.show()

df["Discount (%)"].unique()

"""Scatter Plot"""

sns.scatterplot(
    data=df,
    x="Discount (%)",
    y="Profit"
)

plt.title("Impact of Discount on Profit")
plt.show()

"""Correlation Heatmap"""

numeric_df = df.select_dtypes(
    include="number"
)

corr = numeric_df.corr()

corr

sns.heatmap(
    corr,
    annot=True
)

plt.title("Correlation Heatmap")
plt.show()